### ISSUE TITLE
ReferenceError: milestonesWithDueDatesSorted is not defined

### ISSUE THREAD

**Issue by erikpmp** [thisisarray/milepost-v1#26]
ReferenceError: milestonesWithDueDatesSorted is not defined
    at addIssuesFromMilestonesWithoutDueDates (/Users/erikolson/Documents/code/milepost/src/report-generator.js:315:23)
    at /Users/erikolson/Documents/code/milepost/src/report-generator.js:366:13
    at tryCatcher (/Users/erikolson/Documents/code/milepost/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/erikolson/Documents/code/milepost/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/erikolson/Documents/code/milepost/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/erikolson/Documents/code/milepost/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/erikolson/Documents/code/milepost/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/erikolson/Documents/code/milepost/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/erikolson/Documents/code/milepost/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by brianarray** [comment]
Tested assignments, undid assignment.

**Comment by erikpmp** [comment]
OBE
